using GenieFramework 

include("model.jl")

@genietools 




@handlers begin
    @in x = 1.0
    @in y = 2.0
    @out u_x = []
    @out u_y = []
    @in start = false

    @onchange start begin
        println(start)
    end
    
end

LAYOUT ="""
  <!DOCTYPE html>
  <html>
    <head>
      <meta charset="utf-8">
      <% Stipple.sesstoken() %>
      <title>app</title>
      <% if isfile(joinpath(Genie.config.server_document_root, "css", "genieapp.css")) %>
      <link rel='stylesheet' href='/css/genieapp.css'>
      <% else %>
      <% end %>
      <% if isfile(joinpath(Genie.config.server_document_root, "css", "autogenerated.css")) %>
      <link rel='stylesheet' href='/css/autogenerated.css'>
      <% else %>
      <% end %>
      <style>
        ._genie_logo {
          background:url('https://genieframework.com/logos/genie/logo-simple-with-padding.svg') no-repeat;background-size:40px;
          padding-top:22px;padding-right:10px;color:transparent;font-size:9pt;
        }
        ._genie .row .col-12 { width:50%;margin:auto; }
      </style>
    </head>
    <body>
      <div class='container'>
        <div class='row'>
          <div class='col-12'>
            <% page(model, partial = true, v__cloak = true, [@yield], @iif(:isready)) %>
          </div>
        </div>
      </div>
      <% if isfile(joinpath(Genie.config.server_document_root, "js", "genieapp.js")) %>
      <script src='/js/genieapp.js'></script>
      <% else %>
      <% end %>
    </body>
  </html>
  """


function ui()
    [
    row([
        cell(class="st-module", bignumber("x", :x ) )
        cell(class="st-module", style="color: red;", [
                h6("y1")
                textfield("", :y)
            ])
        cell(class="st-module", [
            h6("ux1")
            slider(0:0.01:0.1, :u_x ; label=true)
        ])
        btn("Start!", percentage=45.0, flat=true, ripple=false, style="color: red;", loading=true, @click("start = !start"))
    ])
    row([
        # cell(class="st-module", plot(:solplot))
        cell(class="st-module", [
            h6("ux")
        ])
        # cell(class="st-module", style="", [
        #         cell(style="font-size:20px;text-align:center;padding-top:50px", latex" \text{\large Lorenz equations} \\ \dot{x}  = \sigma(y-x) \\ \dot{y}  = \rho x - y - xz \\ \dot{z}  = -\beta z + xy "auto )
        # ])
    ])
    row(style="text-align:center; color:#8d99ae;", [
        cell([
            footer(class="text-muted", style="text-align:center", "test")
        ])
    ])
    ]
end

@page("/", ui, LAYOUT)
Server.isrunning() || Server.up()
